### ISSUE TITLE
Uncaught Error: Unimplemented type: 3

### ISSUE THREAD

**Issue by jczaplew** [naturalatlas/tilestrata-vtile#2]
When I create vector tiles, everything appears to be working except when they are ingested into Mapbox GL JS or [Leaflet.MapboxVectorTile](https://github.com/SpatialServer/Leaflet.MapboxVectorTile) I receive the following error : `Uncaught Error: Unimplemented type: 3`.

My Mapnik configuration looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Map[]>
<Map srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">

<Parameters>
  <Parameter name="bounds">-89,-179,89,179</Parameter>
  <Parameter name="center">0,0,1</Parameter>
  <Parameter name="name"><![CDATA[burwell]]></Parameter>
  <Parameter name="description"><![CDATA[burwell]]></Parameter>
  <Parameter name="attribution"><![CDATA[Data providers, UW-Macrostrat, John J Czaplewski <jczaplew@gmail.com>]]></Parameter>
</Parameters>

<Layer name="tiny"
  srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
    <Datasource>
       <Parameter name="type"><![CDATA[postgis]]></Parameter>
       <Parameter name="table"><![CDATA[test]]></Parameter>
       <Parameter name="key_field"><![CDATA[map_id]]></Parameter>
       <Parameter name="geometry_field"><![CDATA[geom]]></Parameter>
       <Parameter name="extent_cache"><![CDATA[auto]]></Parameter>
       <Parameter name="extent"><![CDATA[-179,-89,179,89]]></Parameter>
       <Parameter name="host"><![CDATA[localhost]]></Parameter>
       <Parameter name="port"><![CDATA[5432]]></Parameter>
       <Parameter name="user"><![CDATA[john]]></Parameter>
       <Parameter name="dbname"><![CDATA[burwell]]></Parameter>
       <Parameter name="srid"><![CDATA[4326]]></Parameter>
    </Datasource>
  </Layer>

</Map>

```

This is the function throwing the error:

```
Protobuf.prototype.skip = function(val) {
    // TODO: bounds checking
    var type = val & 0x7;
    switch (type) {
        /* varint */ case Protobuf.Varint: while (this.buf[this.pos++] > 0x7f); break;
        /* 64 bit */ case Protobuf.Int64: this.pos += 8; break;
        /* length */ case Protobuf.Message: var bytes = this.readVarint(); this.pos += bytes; break;
        /* 32 bit */ case Protobuf.Int32: this.pos += 4; break;
        default: throw new Error('Unimplemented type: ' + type);
    }
};
```

I have tried changing the projection of the layer to `3857`, but then it appears as if no data is returned by the renderer (all tiles are empty), whereas when I leave it as WGS84 the tiles are all different sizes, making me believe actual data is being returned.

It's also worth noting that following the example the `README`, raster tiles work just fine.

Any ideas for what may be causing this issue? Thanks!

**Comment by brianreavis** [comment]
Hmm, my hunch is that this relates to: https://github.com/mapbox/mapbox-gl-js/issues/1567. Try adding this to your route and see if it makes a difference (tilestrata-vtile always gzips the pbfs):

``` js
.use(headers({'Content-Encoding': 'gzip'}));
```

https://github.com/naturalatlas/tilestrata-headers

**Comment by jczaplew** [comment]
That solved it! Thanks for the tip!

**Comment by geor-g** [comment]
@brandonreavis Thanks for your work on this! I'm starting with vector tiles, I'm running `nginx` in front of `tilestrata`. I'm checking first if the file exists on disk, if so, let `nginx` serve it directly, if not, passing the request to `tilestrata`. The second case works fine via `.use(headers({'Content-Encoding': 'gzip'}));`, however, I'm wondering, how to handle the first one correctly: Currently I'm using 

```
location ~ \.pbf {
		add_header content-encoding "gzip";
                try_files $uri @tilestrata-backend;
}
```

Is this the way to go?
