### ISSUE TITLE
Is it possible to server vector tile within a .mbtiles file?

### ISSUE THREAD

**Issue by haoliangyu** [naturalatlas/tilestrata-vtile#3]
As described in Mapbox documentation, vector tiles can be stored into a mbtiles file in protobuf format.

**Comment by geor-g** [comment]
I'm interested in this as well: Is this possible?

**Comment by brianreavis** [comment]
It's technically possible, yes, but there's no plugin for it currently. One could be modeled off of [tilestrata-disk](https://github.com/naturalatlas/tilestrata-disk).
