### ISSUE TITLE
`README.md` Sample Code not working

### ISSUE THREAD

**Issue by rtodea** [naturalatlas/tilestrata-vtile#5]
Hi,

I have some trouble understanding the following part from the [sample usage](https://github.com/naturalatlas/tilestrata-vtile/blob/master/README.md#sample-usage):
```
    .route('i.json').use(rasterizer(common, {
        tilesource: ['mylayer', 't.pbf'],
        interactivity: true
    }));
```

First of all, `rasterizer` is not defined.

Secondly, is the JSON here a GeoJSON or a Mapbox Vector Tile decoded from PBF?

**Comment by brianreavis** [comment]
My apologies... `rasterizer` should be `vtileraster` in that example. As for the second question, the JSON is a utfgrid for interactivity (see https://www.mapbox.com/blog/how-interactivity-works-utfgrid/)
